M48
; DRILL file {KiCad (6.0.10)} date Fri Feb 17 15:24:03 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-02-17T15:24:03-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.10)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0157
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0598
%
G90
G05
T1
X4.0Y-3.9
X4.1Y-3.3
X4.2715Y-4.1
X4.4Y-3.9
X4.4Y-4.0
X4.4Y-4.1
X4.4Y-4.7
X4.6Y-3.6
X4.6Y-3.7
X4.8Y-4.0
X4.9Y-3.8
X4.9Y-4.1
X5.3Y-3.1
T2
X4.7Y-2.3
X4.9Y-2.3
T0
M30
